config/routes.rb
Rails.application.routes.draw do
  get '/' => 'messages#new', as: 'messages'
  post '/' => 'messages#create'
  get '/:id' => 'messages#show', as: 'message'
  delete '/:id' => 'messages#destroy'
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessor :body
  attr_readonly :data
  validates_length_of :data, maximum: 16.kilobytes + 32
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAcceptLanguage::AutoLocale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def set_locale
    if params[:lang]
      I18n.locale = params[:lang]
    else
      super
    end
  rescue I18n::InvalidLocale
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.create(message_params)
  end

  def show
    @message = Message.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render 'missing'
  end

  def destroy
    @message = Message.destroy(params[:id])
  end

  private
  def message_params
    params.require(:message).permit(:data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!

%html(lang="#{t('lang-dash')}")

  %head
    %meta(charset='utf-8')
    %meta(name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0')

    / Favicons
    %link(rel='mask-icon' href='favicon.svg' color='#4a90e2')
    %link(rel='apple-touch-icon' href='apple-touch-icon-precomposed.png')
    %link(rel='icon' href='favicon.png')

    / Facebook
    %meta(property='og:url' content='http://www.vua.sh')
    %meta(property='og:type' content='website')
    %meta(property='og:image' content='http://www.vua.sh/fb-icon.png')
    %meta(property='og:description' content="#{t('slogan')}")
    %meta(property='og:site_name' content='Vuash')
    %meta(property='og:title' content='Vuash')
    %meta(property='og:locale' content="#{t('lang-underscore')}")
    %meta(property="fb:app_id" content='1058681947542613')

    // Android
    %meta(name='theme-color' content='#4a90e2')

    / GoSquared
    :javascript
      !function(g,s,q,r,d){r=g[r]=g[r]||function(){(r.q=r.q||[]).push(
      arguments)};d=s.createElement(q);q=s.getElementsByTagName(q)[0];
      d.src='//d1l6p2sc9645hc.cloudfront.net/tracker.js';q.parentNode.
      insertBefore(d,q)}(window,document,'script','_gs');
      _gs('GSN-581018-P');

    / Google Analytics
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-65316487-1', 'auto');
      ga('send', 'pageview');

    %title Vuash - #{t('slogan')}
    %meta(name='description' content="#{t('slogan')}")

    = stylesheet_link_tag 'application', 'data-turbolinks-track' => true, 'media' => 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %div.site-wrap

      %header.site-header(role='banner')
        = link_to messages_path, class: 'logo-vuash', onclick: "_gs('event', 'Clicked Logo link')" do
          %svg(height='30px' viewBox='0 0 106 97')
            %title= t('logo-title')
            %path(id='vuash-mark' fill='#4a90e2' d='M2.99760217e-15,3.99306484 C2.77555756e-15,0.687680951 2.43876573,-0.874545286 5.44713571,0.51377346 L102.89866,43.4862265 C105.905166,44.873685 105.90703,51.1254547 102.89866,52.5137735 L5.44713571,95.4862265 C2.44062987,96.873685 9.88098492e-15,95.3168135 9.65894032e-15,92.0069352 L7.23556427e-15,61.818444 C7.10237572e-15,60.1592869 1.3243002,58.565268 2.94293644,58.2609181 L39.802494,51.3302669 C44,50.9999999 44,44.9999999 39.802494,44.6704158 L2.94293644,37.7397646 C1.31759752,37.4341544 1.21222207e-16,35.8440787 2.71304116e-16,34.1821769 L2.99760217e-15,3.99306484 Z')
          Vuash
        %p.slogan= t('slogan')

      %main.site-body(role='main')= yield

      %footer.site-footer(role='complementary')
        %ul.features

          %li
            %h2= t('footer.features.safety.title')
            %p
              = t('footer.features.safety.text')
              -# TODO: Link to article/wiki about security
                %br
                %a(href="#{t('footer.features.safety.link-href')}" target='_blank' onclick="_gs('event', 'Clicked Safety link')")= t('footer.features.safety.link-text_html')

          %li
            %h2= t('footer.features.open-source.title')
            %p
              = t('footer.features.open-source.text')
              %br
              %a(href="#{t('footer.features.open-source.link-href')}" target='_blank' onclick="_gs('event', 'Clicked Open Source link')")= t('footer.features.open-source.link-text_html')

          %li
            %h2= t('footer.features.donations.title')
            %p
              = t('footer.features.donations.text')
              %br
              %a(href="#{t('footer.features.donations.link-href')}" target='_blank' onclick="_gs('event', 'Clicked Donation link')")= t('footer.features.donations.link-text_html')

app/views/messages/create.html.haml
%div.padded.center.narrow
  = image_tag 'paper.svg', alt: ''
  %h1= t('created-message.title')
  %p= t('created-message.text_html')

  %div.share-link

:coffee
  $(document).trigger('hash', '#{polymorphic_url(@message)}')

app/views/messages/destroy.html.haml
%div.padded
  %pre.message
  %div.wrong-key.center.narrow(aria-hidden='true' style='display: none;')
    = image_tag 'destroyed.svg', alt: ''
    %h1= t('wrong-key.title')
    %p= t('wrong-key.text_html')

  %p.cta
    %svg(width='16px' viewBox='0 0 16 16')
      %title= t('cta.icon-title')
      %path(id='icon-lock' fill='#fff' fill-rule='evenodd' d="M4,7 L4,4 C4,2.34314575 5.33902013,1 7.00166547,1 L8.99833453,1 C10.6561086,1 12,2.34651712 12,4 L12,7 L13,7 L13,15 L3,15 L3,7 L4,7 Z M7.0093689,3 L8.9906311,3 C9.54809015,3 10,3.44266033 10,3.99895656 L10,7 L6,7 L6,3.99895656 C6,3.44724809 6.44335318,3 7.0093689,3 Z M7,10.0093689 C7,9.45190985 7.44386482,9 8,9 C8.55228475,9 9,9.44335318 9,10.0093689 L9,13 L7,13 L7,10.0093689 Z")
    = t('cta.text')
    = link_to t('cta.link-text'), messages_path, onclick: "_gs('event', 'Clicked CTA link at message page')"

:coffee
  $(document).trigger('decrypt', '#{@message.data}')

app/views/messages/missing.html.haml
%div.padded
  %div.not-found.center.narrow
    = image_tag 'notfound.svg', alt: ''
    %h1= t('not-found.title')
    %p= t('not-found.text_html')
  %p.cta
    %svg(width='16px' viewBox='0 0 16 16')
      %title= t('cta.icon-title')
      %path(id='icon-lock' fill='#fff' fill-rule='evenodd' d="M4,7 L4,4 C4,2.34314575 5.33902013,1 7.00166547,1 L8.99833453,1 C10.6561086,1 12,2.34651712 12,4 L12,7 L13,7 L13,15 L3,15 L3,7 L4,7 Z M7.0093689,3 L8.9906311,3 C9.54809015,3 10,3.44266033 10,3.99895656 L10,7 L6,7 L6,3.99895656 C6,3.44724809 6.44335318,3 7.0093689,3 Z M7,10.0093689 C7,9.45190985 7.44386482,9 8,9 C8.55228475,9 9,9.44335318 9,10.0093689 L9,13 L7,13 L7,10.0093689 Z")
    = t('cta.text')
    = link_to t('cta.link-text'), messages_path, onclick: "_gs('event', 'Clicked CTA link at missing page')"

app/views/messages/new.html.haml
%div.validation-error(aria-hidden='true' role='alert')= t('validation-error')

%textarea.new-message-field(autofocus placeholder="#{t('new-message.placeholder')}" maxlength=16384 name='body')

= form_for @message do |f|
  = f.hidden_field :data
  %div.padded
    %button.bt-blue
      %svg(width='16px' viewBox='0 0 16 16')
        %title= t('new-message.icon-title')
        %path(id='icon-lock' fill='#fff' fill-rule='evenodd' d="M4,7 L4,4 C4,2.34314575 5.33902013,1 7.00166547,1 L8.99833453,1 C10.6561086,1 12,2.34651712 12,4 L12,7 L13,7 L13,15 L3,15 L3,7 L4,7 Z M7.0093689,3 L8.9906311,3 C9.54809015,3 10,3.44266033 10,3.99895656 L10,7 L6,7 L6,3.99895656 C6,3.44724809 6.44335318,3 7.0093689,3 Z M7,10.0093689 C7,9.45190985 7.44386482,9 8,9 C8.55228475,9 9,9.44335318 9,10.0093689 L9,13 L7,13 L7,10.0093689 Z")
      = t('new-message.button-text')

app/views/messages/show.html.haml
%div.padded.center.narrow
  = image_tag 'envelope.svg', alt: ''
  %h1= t('open-message.title')
  %p= t('open-message.text_html')
  = form_for @message, method: 'delete' do |f|
    = f.submit t('open-message.button-text'), class: 'bt-blue', onclick: "_gs('event', 'Clicked Read Message link')"